// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Creates a new role
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	// =============================================
	// User Queries
	// =============================================
	// Creates a new user and returns the created record
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Soft delete is not implemented, this is hard delete
	DeleteUser(ctx context.Context, id uuid.UUID) error
	// Checks if a user with the given email exists
	ExistsByEmail(ctx context.Context, email string) (bool, error)
	// Checks if a user with the given username exists
	ExistsByUsername(ctx context.Context, username string) (bool, error)
	// Retrieves the default role for new users (STUDENT)
	GetDefaultRole(ctx context.Context) (Role, error)
	// Retrieves flattened permission actions for a role (e.g., "users:read", "users:write")
	GetPermissionActionsByRoleID(ctx context.Context, roleID uuid.UUID) ([]interface{}, error)
	// =============================================
	// Permission Queries
	// =============================================
	// Retrieves all permissions for a given role
	GetPermissionsByRoleID(ctx context.Context, roleID uuid.UUID) ([]GetPermissionsByRoleIDRow, error)
	// Retrieves a role by its code (e.g., "STUDENT", "ADMIN")
	GetRoleByCode(ctx context.Context, code string) (Role, error)
	// =============================================
	// Role Queries
	// =============================================
	// Retrieves a role by its UUID
	GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error)
	// Retrieves a user by their email address
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	// Retrieves a user by email OR username (for login)
	GetUserByEmailOrUsername(ctx context.Context, email string) (GetUserByEmailOrUsernameRow, error)
	// Retrieves a user by their UUID
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	// Retrieves a user by their username
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	// Updates the last login timestamp for a user
	UpdateLastLogin(ctx context.Context, id uuid.UUID) error
	// Updates an existing user
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
