// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Permission struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	RoleID     uuid.UUID        `db:"role_id" json:"role_id"`
	ResourceID uuid.UUID        `db:"resource_id" json:"resource_id"`
	Actions    []byte           `db:"actions" json:"actions"`
	CreatedAt  pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Resource struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Name        string    `db:"name" json:"name"`
	Code        string    `db:"code" json:"code"`
	ApiUri      *string   `db:"api_uri" json:"api_uri"`
	Description *string   `db:"description" json:"description"`
}

type Role struct {
	ID          uuid.UUID        `db:"id" json:"id"`
	Name        string           `db:"name" json:"name"`
	Code        string           `db:"code" json:"code"`
	Description *string          `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type User struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	RoleID    uuid.UUID        `db:"role_id" json:"role_id"`
	Email     string           `db:"email" json:"email"`
	Username  string           `db:"username" json:"username"`
	Password  string           `db:"password" json:"password"`
	FullName  string           `db:"full_name" json:"full_name"`
	Phone     *string          `db:"phone" json:"phone"`
	Avatar    *string          `db:"avatar" json:"avatar"`
	IsActive  *bool            `db:"is_active" json:"is_active"`
	LastLogin pgtype.Timestamp `db:"last_login" json:"last_login"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
