// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: permission.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getPermissionActionsByRoleID = `-- name: GetPermissionActionsByRoleID :many
SELECT DISTINCT
    r.code || ':' || action AS permission
FROM permissions p
JOIN resources r ON p.resource_id = r.id,
LATERAL jsonb_array_elements_text(p.actions) AS action
WHERE p.role_id = $1
`

// Retrieves flattened permission actions for a role (e.g., "users:read", "users:write")
func (q *Queries) GetPermissionActionsByRoleID(ctx context.Context, roleID uuid.UUID) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, getPermissionActionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []interface{}{}
	for rows.Next() {
		var permission interface{}
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionsByRoleID = `-- name: GetPermissionsByRoleID :many

SELECT 
    p.id,
    p.role_id,
    p.resource_id,
    p.actions,
    r.code AS resource_code,
    r.name AS resource_name
FROM permissions p
JOIN resources r ON p.resource_id = r.id
WHERE p.role_id = $1
`

type GetPermissionsByRoleIDRow struct {
	ID           uuid.UUID `db:"id" json:"id"`
	RoleID       uuid.UUID `db:"role_id" json:"role_id"`
	ResourceID   uuid.UUID `db:"resource_id" json:"resource_id"`
	Actions      []byte    `db:"actions" json:"actions"`
	ResourceCode string    `db:"resource_code" json:"resource_code"`
	ResourceName string    `db:"resource_name" json:"resource_name"`
}

// =============================================
// Permission Queries
// =============================================
// Retrieves all permissions for a given role
func (q *Queries) GetPermissionsByRoleID(ctx context.Context, roleID uuid.UUID) ([]GetPermissionsByRoleIDRow, error) {
	rows, err := q.db.Query(ctx, getPermissionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPermissionsByRoleIDRow{}
	for rows.Next() {
		var i GetPermissionsByRoleIDRow
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.ResourceID,
			&i.Actions,
			&i.ResourceCode,
			&i.ResourceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
