// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: role.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (name, code, description)
VALUES ($1, $2, $3)
RETURNING id, name, code, description, created_at
`

type CreateRoleParams struct {
	Name        string  `db:"name" json:"name"`
	Code        string  `db:"code" json:"code"`
	Description *string `db:"description" json:"description"`
}

// Creates a new role
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Code, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getDefaultRole = `-- name: GetDefaultRole :one
SELECT id, name, code, description, created_at FROM roles WHERE code = 'STUDENT' LIMIT 1
`

// Retrieves the default role for new users (STUDENT)
func (q *Queries) GetDefaultRole(ctx context.Context) (Role, error) {
	row := q.db.QueryRow(ctx, getDefaultRole)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByCode = `-- name: GetRoleByCode :one
SELECT id, name, code, description, created_at FROM roles WHERE code = $1
`

// Retrieves a role by its code (e.g., "STUDENT", "ADMIN")
func (q *Queries) GetRoleByCode(ctx context.Context, code string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByCode, code)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one

SELECT id, name, code, description, created_at FROM roles WHERE id = $1
`

// =============================================
// Role Queries
// =============================================
// Retrieves a role by its UUID
func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
