// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    id,
    role_id,
    email,
    username,
    password,
    full_name,
    phone,
    avatar,
    is_active,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, role_id, email, username, password, full_name, phone, avatar, is_active, last_login, created_at, updated_at
`

type CreateUserParams struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	RoleID    uuid.UUID        `db:"role_id" json:"role_id"`
	Email     string           `db:"email" json:"email"`
	Username  string           `db:"username" json:"username"`
	Password  string           `db:"password" json:"password"`
	FullName  string           `db:"full_name" json:"full_name"`
	Phone     *string          `db:"phone" json:"phone"`
	Avatar    *string          `db:"avatar" json:"avatar"`
	IsActive  *bool            `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

// =============================================
// User Queries
// =============================================
// Creates a new user and returns the created record
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.RoleID,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.FullName,
		arg.Phone,
		arg.Avatar,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.FullName,
		&i.Phone,
		&i.Avatar,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

// Soft delete is not implemented, this is hard delete
func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const existsByEmail = `-- name: ExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1) AS exists
`

// Checks if a user with the given email exists
func (q *Queries) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, existsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsByUsername = `-- name: ExistsByUsername :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1) AS exists
`

// Checks if a user with the given username exists
func (q *Queries) ExistsByUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, existsByUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT 
    u.id, u.role_id, u.email, u.username, u.password, u.full_name, u.phone, u.avatar, u.is_active, u.last_login, u.created_at, u.updated_at,
    r.name AS role_name,
    r.code AS role_code
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.email = $1
`

type GetUserByEmailRow struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	RoleID    uuid.UUID        `db:"role_id" json:"role_id"`
	Email     string           `db:"email" json:"email"`
	Username  string           `db:"username" json:"username"`
	Password  string           `db:"password" json:"password"`
	FullName  string           `db:"full_name" json:"full_name"`
	Phone     *string          `db:"phone" json:"phone"`
	Avatar    *string          `db:"avatar" json:"avatar"`
	IsActive  *bool            `db:"is_active" json:"is_active"`
	LastLogin pgtype.Timestamp `db:"last_login" json:"last_login"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	RoleName  *string          `db:"role_name" json:"role_name"`
	RoleCode  *string          `db:"role_code" json:"role_code"`
}

// Retrieves a user by their email address with role info
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.FullName,
		&i.Phone,
		&i.Avatar,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleName,
		&i.RoleCode,
	)
	return i, err
}

const getUserByEmailOrUsername = `-- name: GetUserByEmailOrUsername :one
SELECT 
    u.id, u.role_id, u.email, u.username, u.password, u.full_name, u.phone, u.avatar, u.is_active, u.last_login, u.created_at, u.updated_at,
    r.name AS role_name,
    r.code AS role_code
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.email = $1 OR u.username = $1
`

type GetUserByEmailOrUsernameRow struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	RoleID    uuid.UUID        `db:"role_id" json:"role_id"`
	Email     string           `db:"email" json:"email"`
	Username  string           `db:"username" json:"username"`
	Password  string           `db:"password" json:"password"`
	FullName  string           `db:"full_name" json:"full_name"`
	Phone     *string          `db:"phone" json:"phone"`
	Avatar    *string          `db:"avatar" json:"avatar"`
	IsActive  *bool            `db:"is_active" json:"is_active"`
	LastLogin pgtype.Timestamp `db:"last_login" json:"last_login"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	RoleName  *string          `db:"role_name" json:"role_name"`
	RoleCode  *string          `db:"role_code" json:"role_code"`
}

// Retrieves a user by email OR username (for login) with role info
func (q *Queries) GetUserByEmailOrUsername(ctx context.Context, email string) (GetUserByEmailOrUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailOrUsername, email)
	var i GetUserByEmailOrUsernameRow
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.FullName,
		&i.Phone,
		&i.Avatar,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleName,
		&i.RoleCode,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
    u.id, u.role_id, u.email, u.username, u.password, u.full_name, u.phone, u.avatar, u.is_active, u.last_login, u.created_at, u.updated_at,
    r.name AS role_name,
    r.code AS role_code
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.id = $1
`

type GetUserByIDRow struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	RoleID    uuid.UUID        `db:"role_id" json:"role_id"`
	Email     string           `db:"email" json:"email"`
	Username  string           `db:"username" json:"username"`
	Password  string           `db:"password" json:"password"`
	FullName  string           `db:"full_name" json:"full_name"`
	Phone     *string          `db:"phone" json:"phone"`
	Avatar    *string          `db:"avatar" json:"avatar"`
	IsActive  *bool            `db:"is_active" json:"is_active"`
	LastLogin pgtype.Timestamp `db:"last_login" json:"last_login"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	RoleName  *string          `db:"role_name" json:"role_name"`
	RoleCode  *string          `db:"role_code" json:"role_code"`
}

// Retrieves a user by their UUID with role info
func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.FullName,
		&i.Phone,
		&i.Avatar,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleName,
		&i.RoleCode,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT 
    u.id, u.role_id, u.email, u.username, u.password, u.full_name, u.phone, u.avatar, u.is_active, u.last_login, u.created_at, u.updated_at,
    r.name AS role_name,
    r.code AS role_code
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.username = $1
`

type GetUserByUsernameRow struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	RoleID    uuid.UUID        `db:"role_id" json:"role_id"`
	Email     string           `db:"email" json:"email"`
	Username  string           `db:"username" json:"username"`
	Password  string           `db:"password" json:"password"`
	FullName  string           `db:"full_name" json:"full_name"`
	Phone     *string          `db:"phone" json:"phone"`
	Avatar    *string          `db:"avatar" json:"avatar"`
	IsActive  *bool            `db:"is_active" json:"is_active"`
	LastLogin pgtype.Timestamp `db:"last_login" json:"last_login"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	RoleName  *string          `db:"role_name" json:"role_name"`
	RoleCode  *string          `db:"role_code" json:"role_code"`
}

// Retrieves a user by their username with role info
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.FullName,
		&i.Phone,
		&i.Avatar,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleName,
		&i.RoleCode,
	)
	return i, err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users SET last_login = NOW() WHERE id = $1
`

// Updates the last login timestamp for a user
func (q *Queries) UpdateLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    email = COALESCE($2, email),
    username = COALESCE($3, username),
    password = COALESCE($4, password),
    full_name = COALESCE($5, full_name),
    phone = COALESCE($6, phone),
    avatar = COALESCE($7, avatar),
    is_active = COALESCE($8, is_active),
    updated_at = NOW()
WHERE id = $1
RETURNING id, role_id, email, username, password, full_name, phone, avatar, is_active, last_login, created_at, updated_at
`

type UpdateUserParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Email    string    `db:"email" json:"email"`
	Username string    `db:"username" json:"username"`
	Password string    `db:"password" json:"password"`
	FullName string    `db:"full_name" json:"full_name"`
	Phone    *string   `db:"phone" json:"phone"`
	Avatar   *string   `db:"avatar" json:"avatar"`
	IsActive *bool     `db:"is_active" json:"is_active"`
}

// Updates an existing user
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.FullName,
		arg.Phone,
		arg.Avatar,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.FullName,
		&i.Phone,
		&i.Avatar,
		&i.IsActive,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
