#!/bin/bash
# =========================================================
# Sync Schema from Gateway (Drizzle) to Worker (SQLC)
# Gateway is the SOURCE OF TRUTH for database schema
# =========================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVER_DIR="$(dirname "$SCRIPT_DIR")"

GATEWAY_SCHEMA="$SERVER_DIR/gateway/drizzle"
WORKER_SCHEMA_DIR="$SERVER_DIR/worker/internal/adapter/storage/postgres/db"

echo "📦 Syncing schema from Gateway to Worker..."
echo "   Source: $GATEWAY_SCHEMA"
echo "   Target: $WORKER_SCHEMA_DIR"

# Check if Gateway has SQL migrations
if [ ! -d "$GATEWAY_SCHEMA" ]; then
    echo "❌ Error: Gateway drizzle folder not found!"
    exit 1
fi

# Ensure target directory exists
mkdir -p "$WORKER_SCHEMA_DIR"

# Concatenate all migration files into schema.sql
echo "-- =============================================" > "$WORKER_SCHEMA_DIR/schema.sql"
echo "-- AUTO-GENERATED FROM GATEWAY MIGRATIONS" >> "$WORKER_SCHEMA_DIR/schema.sql"
echo "-- DO NOT EDIT THIS FILE DIRECTLY!" >> "$WORKER_SCHEMA_DIR/schema.sql"
echo "-- Source: gateway/drizzle/*.sql" >> "$WORKER_SCHEMA_DIR/schema.sql"
echo "-- =============================================" >> "$WORKER_SCHEMA_DIR/schema.sql"
echo "" >> "$WORKER_SCHEMA_DIR/schema.sql"

# Append each .sql migration file (sorted by name)
for file in "$GATEWAY_SCHEMA"/*.sql; do
    if [ -f "$file" ]; then
        echo "-- From: $(basename "$file")" >> "$WORKER_SCHEMA_DIR/schema.sql"
        cat "$file" >> "$WORKER_SCHEMA_DIR/schema.sql"
        echo "" >> "$WORKER_SCHEMA_DIR/schema.sql"
    fi
done

echo "✅ Schema synced successfully!"
echo ""
echo "📋 Next steps:"
echo "   cd worker && sqlc generate"
