<# 
.SYNOPSIS
    Sync Schema from Gateway (Drizzle) to Worker (SQLC)
    Gateway is the SOURCE OF TRUTH for database schema
#>

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ServerDir = Split-Path -Parent $ScriptDir

$GatewaySchema = Join-Path $ServerDir "gateway\drizzle"
$WorkerSchemaDir = Join-Path $ServerDir "worker\internal\adapter\storage\postgres\db"
$WorkerSchemaFile = Join-Path $WorkerSchemaDir "schema.sql"

Write-Host "📦 Syncing schema from Gateway to Worker..." -ForegroundColor Cyan
Write-Host "   Source: $GatewaySchema"
Write-Host "   Target: $WorkerSchemaDir"

# Check if Gateway has SQL migrations
if (-not (Test-Path $GatewaySchema)) {
    Write-Host "❌ Error: Gateway drizzle folder not found!" -ForegroundColor Red
    exit 1
}

# Ensure target directory exists
if (-not (Test-Path $WorkerSchemaDir)) {
    New-Item -ItemType Directory -Path $WorkerSchemaDir -Force | Out-Null
}

# Create header for schema.sql
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$header = "-- =============================================`n"
$header += "-- AUTO-GENERATED FROM GATEWAY MIGRATIONS`n"
$header += "-- DO NOT EDIT THIS FILE DIRECTLY!`n"
$header += "-- Source: gateway/drizzle/*.sql`n"
$header += "-- Generated: $timestamp`n"
$header += "-- =============================================`n`n"

Set-Content -Path $WorkerSchemaFile -Value $header -Encoding UTF8 -NoNewline

# Append each .sql migration file (sorted by name)
$sqlFiles = Get-ChildItem -Path $GatewaySchema -Filter "*.sql" | Sort-Object Name

foreach ($file in $sqlFiles) {
    Write-Host "   Processing: $($file.Name)" -ForegroundColor Gray
    Add-Content -Path $WorkerSchemaFile -Value "-- From: $($file.Name)"
    Get-Content -Path $file.FullName | Add-Content -Path $WorkerSchemaFile
    Add-Content -Path $WorkerSchemaFile -Value ""
}

Write-Host ""
Write-Host "✅ Schema synced successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "📋 Next steps:" -ForegroundColor Yellow
Write-Host "   cd worker; sqlc generate"
